# Generated by Django 3.0.8 on 2020-08-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('author', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'bloginfo',
            },
        ),
    ]
