# Generated by Django 3.0.8 on 2020-08-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='JournalModel',
        ),
        migrations.AlterModelTable(
            name='journalmodel',
            table='Journalinfo',
        ),
    ]
